// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintPlatform.Loyalty.Data;

#nullable disable

namespace PrintPlatform.Loyalty.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    partial class LoyaltyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.LoyaltyMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivePoints")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedOrderCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentTierId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("integer");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTierId");

                    b.HasIndex("ExternalUserId")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.ToTable("loy_members", (string)null);
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.LoyaltyTier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BenefitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("loy_tiers", (string)null);
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.PointsLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("loy_ledger", (string)null);
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.Redemption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LoyaltyMemberId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PointsUsed")
                        .HasColumnType("integer");

                    b.Property<long>("RewardId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RewardId");

                    b.ToTable("loy_redemptions", (string)null);
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.Referral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferredUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferrerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ReferredUserId");

                    b.HasIndex("ReferrerId");

                    b.ToTable("loy_referrals", (string)null);
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.Reward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("loy_rewards", (string)null);
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.LoyaltyMember", b =>
                {
                    b.HasOne("PrintPlatform.Loyalty.Models.LoyaltyTier", "CurrentTier")
                        .WithMany("Members")
                        .HasForeignKey("CurrentTierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentTier");
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.PointsLedger", b =>
                {
                    b.HasOne("PrintPlatform.Loyalty.Models.LoyaltyMember", "Member")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.Redemption", b =>
                {
                    b.HasOne("PrintPlatform.Loyalty.Models.LoyaltyMember", null)
                        .WithMany("Redemptions")
                        .HasForeignKey("LoyaltyMemberId");

                    b.HasOne("PrintPlatform.Loyalty.Models.LoyaltyMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintPlatform.Loyalty.Models.Reward", "Reward")
                        .WithMany("Redemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.LoyaltyMember", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.LoyaltyTier", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PrintPlatform.Loyalty.Models.Reward", b =>
                {
                    b.Navigation("Redemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
